### ISSUE TITLE
Suggestion : The version order will better in numerical order

### ISSUE THREAD

**Issue by zhangenming** [mozilla/releases_insights#54] opened 2024-04-18 03:24 UTC
https://whattrainisitnow.com/calendar/#Future_branch_dates
![image](https://github.com/mozilla/releases_insights/assets/21235555/7dc64c3d-2e04-4b11-b6a7-596c66c973ac)

**Comment by pascalchevrel** [comment] 2024-04-18 07:28
Thanks for reporting, this was caused by the replacement of the 125.0 release by a 125.0.1 release which made the sorting different, this is fixed on production now.

**Closed by pascalchevrel** 2024-04-18 07:28 UTC
